### ISSUE TITLE
Additional Information for pokemon-pop-up

### ISSUE THREAD

**Issue by exilhanseat** [exilhanseat/PokemonBotMap#11]
![image](https://user-images.githubusercontent.com/14312750/54019204-e5e82780-418a-11e9-933e-786b8611fab1.png)
As a user I want to get instructions how to get to the pokemon on the map. 
If the time til hidden is less then 5 Minutes I want to see the remaining time in Red

**Comment by masterofchi** [comment]
Duplicate of https://github.com/masterofchi/PokemonBotMap/issues/10
