### ISSUE TITLE
Additional information for Map

### ISSUE THREAD

**Issue by exilhanseat** [exilhanseat/PokemonBotMap#12]
As a user I want to see additional information for the pokemon:
- A symobl to see that this is a pokemon from a raid (a small egg? the gym badge?)
- If it's from a quest (a PokeStop Symbol)
- If there is a raid, which already has interests, show the number of interests on the map

**Comment by masterofchi** [comment]
- [ ] A symobl to see that this is a pokemon from a raid (a small egg? the gym badge?)
- [ ] If it's from a quest (a PokeStop Symbol)
- [ ] If there is a raid, which already has interests, show the number of interests on the map

**Comment by masterofchi** [comment]
Implemented with https://github.com/exilhanseat/PokemonBotMap/pull/19
