### ISSUE TITLE
Create more Menus for Layers

### ISSUE THREAD

**Issue by exilhanseat** [exilhanseat/PokemonBotMap#13]
- 1 Menu for Raids (Ex-Raids, Level 5, etc.)
- 1 Menu for Gyms and Pokemon
- 1 Menu for Quests Quests (Pokemon, Stardust, ...)
- 1 Menu for Map Styles

**Comment by masterofchi** [comment]
I'd rather not add a ton of new menus, as it is impractical for mobile view. Instead I would like to implement a new search menu at top/center where you can search for pokemon with autocomplete and have your map view filtered. Additionally you could add search functionality for quests (type of quest, rewards...) and gyms (free spaces, color). The raid menu could be reworked by using the search panel as filter (e.g. show only level 4 and 5 raids).

In the end, the layer menu gets a cleanup as there is only one checkbox for raids, gyms, pokemon and quests. The map style should stay where they are.
The 'filter' menu can get some more real estate and could be used for fine tuning your view.

**Comment by masterofchi** [comment]
solved in https://github.com/exilhanseat/PokemonBotMap/pull/22
